CREATE SCHEMA IF NOT EXISTS ponntrix_pharmacy;
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1. PHARMACY MASTER
CREATE TABLE IF NOT EXISTS ponntrix_pharmacy.pharmacy (
    pharmacy_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    pharmacy_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    pharmacy_name character varying(100) NOT NULL,
    hospital_id integer, -- References ponntrix_hospital.hospital(hospital_id) if internal
    provider_type character varying(30) NOT NULL, -- 'INTERNAL' or 'EXTERNAL'
    partner_name character varying(100), -- or franchise ID
    license_number character varying(100) NOT NULL,
    pharmacist_id integer NOT NULL, -- employee id with pharmacist role
    contact_email character varying(50) NOT NULL,
    contact_phone character varying(12) NOT NULL,
    accepts_online_orders boolean DEFAULT false,
    home_delivery boolean DEFAULT false,
    api_enabled boolean DEFAULT false,
    api_endpoint TEXT,
    is_active boolean DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT pharmacy_pkey PRIMARY KEY (pharmacy_id),
    CONSTRAINT fk_pharmacy_hospital FOREIGN KEY (hospital_id)
        REFERENCES ponntrix_hospital.hospital(hospital_id)
        ON UPDATE NO ACTION
        ON DELETE SET NULL
);

-- 2. PHARMACY ITEM DETAILS (1:1 with ponntrix_lab.order_items)
CREATE TABLE IF NOT EXISTS ponntrix_pharmacy.pharmacy_item_details (
    pharmacy_item_detail_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_items_id integer NOT NULL UNIQUE, -- 1:1 relationship with order_items
    pharmacy_id integer,
    inventory_id integer, -- References ponntrix_lab.pharmacy_inventory(inventory_id)
    dosage_form character varying(50),   -- Tablet, Capsule, Syrup, etc.
    dosage_quantity numeric(10,2),       -- 1.0, 5.0, 2.0
    dispense_status character varying(30) DEFAULT 'PENDING' NOT NULL, -- 'PENDING', 'PACKED', 'DISPATCHED', 'CANCELLED'
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT pharmacy_item_details_pkey PRIMARY KEY (pharmacy_item_detail_id),
    CONSTRAINT fk_pharmacy_details_order_item FOREIGN KEY (order_items_id)
        REFERENCES ponntrix_lab.order_items(order_items_id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_pharmacy_details_pharmacy FOREIGN KEY (pharmacy_id)
        REFERENCES ponntrix_pharmacy.pharmacy(pharmacy_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- 3. PHARMACY ORDER ASSIGNMENT
CREATE TABLE IF NOT EXISTS ponntrix_pharmacy.pharmacy_order_assignment (
    pharmacy_assignment_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_id integer NOT NULL,
    doctor_prescription_id integer, -- Optional if order was direct purchase
    pharmacy_id integer NOT NULL,
    assignment_status character varying(30) NOT NULL, -- 'ASSIGNED', 'ACCEPTED', 'PACKING_PENDING', 'PACKED', 'DISPATCHED', 'READY_FOR_PICKUP', 'COMPLETED', 'CANCELLED'
    remarks TEXT,
    assigned_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    assigned_by integer,
    CONSTRAINT pharmacy_order_assignment_pkey PRIMARY KEY (pharmacy_assignment_id),
    CONSTRAINT fk_pharmacy_assignment_order FOREIGN KEY (order_id)
        REFERENCES ponntrix_lab.orders(order_id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_pharmacy_assignment_prescription FOREIGN KEY (doctor_prescription_id)
        REFERENCES ponntrix_hospital.doctor_prescription(doctor_prescription_id)
        ON UPDATE NO ACTION
        ON DELETE SET NULL,
    CONSTRAINT fk_pharmacy_assignment_pharmacy FOREIGN KEY (pharmacy_id)
        REFERENCES ponntrix_pharmacy.pharmacy(pharmacy_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- ==========================================
-- INDEXES FOR PERFORMANCE
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_pharmacy_order_lookup
    ON ponntrix_pharmacy.pharmacy_order_assignment(order_id, pharmacy_id, assignment_status);