CREATE SCHEMA IF NOT EXISTS ponntrix_lab;
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1. LAB MASTER TABLE
CREATE TABLE IF NOT EXISTS ponntrix_lab.lab (
    lab_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    lab_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    lab_name character varying(100) NOT NULL,
    hospital_id integer,
    provider_type character varying(30) NOT NULL, -- 'INTERNAL' or 'EXTERNAL'
    partner_name character varying(100),
    license_number character varying(100) NOT NULL,
    lab_technician_id integer NOT NULL, -- employee id whose role is lab technician
    contact_email character varying(50) NOT NULL,
    contact_phone character varying(12) NOT NULL,
    accepts_online_orders boolean DEFAULT false,
    api_enabled boolean DEFAULT false,
    api_endpoint TEXT,
    is_active boolean DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT lab_pkey PRIMARY KEY (lab_id)
);

-- 2. LAB SERVICE CATALOG
CREATE TABLE IF NOT EXISTS ponntrix_lab.lab_service (
    lab_service_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    lab_id integer NOT NULL,
    service_name character varying(100) NOT NULL,
    service_code character varying(30) NOT NULL UNIQUE,
    service_description TEXT,
    service_price numeric(10,2) NOT NULL,
    is_fasting_required boolean DEFAULT false,
    sample_type character varying(50), -- Blood, Urine, Swab, etc.
    is_active boolean DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT lab_service_pkey PRIMARY KEY (lab_service_id),
    CONSTRAINT fk_lab_service_lab FOREIGN KEY (lab_id)
        REFERENCES ponntrix_lab.lab(lab_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- 3. ORDERS MASTER
CREATE TABLE IF NOT EXISTS ponntrix_lab.orders (
    order_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    order_type character varying(30) NOT NULL, -- 'LAB' or 'PHARMACY'
    order_status character varying(30) NOT NULL, -- 'PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'
    patient_id integer NOT NULL,
    doctor_id integer NOT NULL,
    hospital_id integer,
    total_amount numeric(10,2) NOT NULL,
    delivery_type character varying(30) NOT NULL, -- 'DOOR_DELIVERY', 'PHARMACY_PICKUP', 'LAB_VISIT'
    contact_person_id integer NOT NULL, -- operations employee
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);

-- 5. ORDER ITEMS
CREATE TABLE IF NOT EXISTS ponntrix_lab.order_items (
    order_items_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_item_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    order_id integer NOT NULL,
    lab_service_id integer, -- Links to lab catalog if LAB order
    inventory_id integer,   -- Links to pharmacy inventory if PHARMACY order
    item_name character varying(100) NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    quantity integer DEFAULT 1 NOT NULL CHECK (quantity > 0),
    total_price numeric(10,2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT order_items_pkey PRIMARY KEY (order_items_id),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id)
        REFERENCES ponntrix_lab.orders(order_id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_order_items_lab_service FOREIGN KEY (lab_service_id)
        REFERENCES ponntrix_lab.lab_service(lab_service_id)
        ON UPDATE NO ACTION
        ON DELETE SET NULL,
    CONSTRAINT fk_order_items_inventory FOREIGN KEY (inventory_id)
        REFERENCES ponntrix_lab.pharmacy_inventory(inventory_id)
        ON UPDATE NO ACTION
        ON DELETE SET NULL
);

-- 6. LAB ITEM DETAILS (1:1 with order_items)
CREATE TABLE IF NOT EXISTS ponntrix_lab.lab_item_details (
    lab_item_detail_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_items_id integer NOT NULL UNIQUE, -- Corrected 1:1 FK column name
    lab_id integer,
    sample_type character varying(50),
    is_fasting_required boolean DEFAULT false,
    item_status character varying(30) DEFAULT 'PENDING' NOT NULL, -- 'PENDING', 'SAMPLE_COLLECTED', 'PROCESSING', 'COMPLETED'
    sample_collected_at TIMESTAMPTZ,
    report_file_url TEXT,
    special_instructions TEXT,
    created_by integer,
    updated_by integer,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT lab_item_details_pkey PRIMARY KEY (lab_item_detail_id),
    CONSTRAINT fk_lab_details_item FOREIGN KEY (order_items_id)
        REFERENCES ponntrix_lab.order_items(order_items_id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_lab_details_lab FOREIGN KEY (lab_id)
        REFERENCES ponntrix_lab.lab(lab_id)
        ON UPDATE NO ACTION
        ON DELETE SET NULL
);

-- 7. LAB ORDER ASSIGNMENT
CREATE TABLE IF NOT EXISTS ponntrix_lab.lab_order_assignment (
    lab_assignment_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    order_id integer NOT NULL,
    lab_id integer NOT NULL,
    hospital_id integer, -- Fixed: Changed from UUID to integer to match hospital_id references
    assignment_status character varying(30) NOT NULL, -- 'ASSIGNED', 'ACCEPTED', 'COLLECTION_PENDING', 'SAMPLE_COLLECTED', 'PROCESSING', 'COMPLETED', 'CANCELLED'
    remarks TEXT,
    sample_collection_technician_name character varying(50),
    sample_collection_technician_number character varying(20),
    assigned_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    assigned_by integer,
    CONSTRAINT lab_order_assignment_pkey PRIMARY KEY (lab_assignment_id),
    CONSTRAINT fk_lab_order_assignment_order FOREIGN KEY (order_id)
        REFERENCES ponntrix_lab.orders(order_id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_lab_order_assignment_lab FOREIGN KEY (lab_id)
        REFERENCES ponntrix_lab.lab(lab_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- ==========================================
-- INDEXES FOR PERFORMANCE
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_orders_patient_status ON ponntrix_lab.orders(patient_id, order_status);
CREATE INDEX IF NOT EXISTS idx_pharmacy_inventory_lookup ON ponntrix_lab.pharmacy_inventory(medicine_name, expiry_date);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON ponntrix_lab.order_items(order_id);