CREATE SCHEMA IF NOT EXISTS ponntrix_hospital;
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1. ONBOARDING STATUS
CREATE TABLE IF NOT EXISTS ponntrix_hospital.onboarding_status (
    onboarding_status_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    onboarding_status_name character varying(20) NOT NULL, -- 'PENDING','UNDER_REVIEW','APPROVED','REJECTED'
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT onboarding_status_pkey PRIMARY KEY (onboarding_status_id)
);

-- 2. DAY OF WEEK
CREATE TABLE IF NOT EXISTS ponntrix_hospital.day_of_week (
    day_of_week_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    days_of_week_name character varying(20) NOT NULL, -- MONDAY, TUESDAY...
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT day_of_week_pkey PRIMARY KEY (day_of_week_id)
);

-- 3. COUNTRY
CREATE TABLE IF NOT EXISTS ponntrix_hospital.country (
    country_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    country_name character varying(50) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_by integer,
    CONSTRAINT country_pkey PRIMARY KEY (country_id)
);

-- 4. STATE
CREATE TABLE IF NOT EXISTS ponntrix_hospital.state (
    state_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    state_name character varying(50) NOT NULL,
    country_id integer NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_by integer,
    CONSTRAINT state_pkey PRIMARY KEY (state_id),
    CONSTRAINT country_state_fk_key FOREIGN KEY (country_id)
        REFERENCES ponntrix_hospital.country(country_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- 5. CITY
CREATE TABLE IF NOT EXISTS ponntrix_hospital.city (
    city_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    city_name character varying(50) NOT NULL,
    state_id integer NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_by integer,
    CONSTRAINT city_pkey PRIMARY KEY (city_id),
    CONSTRAINT city_state_fk_key FOREIGN KEY (state_id)
        REFERENCES ponntrix_hospital.state(state_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- 6. AREA
CREATE TABLE IF NOT EXISTS ponntrix_hospital.area (
    area_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    area_name character varying(50) NOT NULL,
    city_id integer NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_by integer,
    CONSTRAINT area_pkey PRIMARY KEY (area_id),
    CONSTRAINT area_city_fk_key FOREIGN KEY (city_id)
        REFERENCES ponntrix_hospital.city(city_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- 7. LANGUAGES
CREATE TABLE IF NOT EXISTS ponntrix_hospital.languages (
    language_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    language_name character varying(50) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_by integer,
    CONSTRAINT language_pkey PRIMARY KEY (language_id)
);

-- 8. QUALIFICATION
CREATE TABLE IF NOT EXISTS ponntrix_hospital.qualification (
    qualification_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    qualification_name character varying(50) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_by integer,
    CONSTRAINT qualification_pkey PRIMARY KEY (qualification_id)
);

-- 9. SPECIALIZATION
CREATE TABLE IF NOT EXISTS ponntrix_hospital.specialization (
    specialization_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    specialization_name character varying(50) NOT NULL,
    qualification_id integer NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_by integer,
    CONSTRAINT specialization_pkey PRIMARY KEY (specialization_id),
    CONSTRAINT specialization_qualification_fk_key FOREIGN KEY (qualification_id)
        REFERENCES ponntrix_hospital.qualification(qualification_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- 10. HOSPITAL
CREATE TABLE IF NOT EXISTS ponntrix_hospital.hospital (
    hospital_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    hospital_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    hospital_type character varying(20) NOT NULL, -- HOSPITAL, CLINIC, MULTI_SPECIALITY
    hospital_name character varying(250) NOT NULL,
    registration_number character varying(100),
    gst_number character varying(50),
    established_year integer,
    hospital_phone character varying(20),
    hospital_email character varying(50),
    website character varying(200),
    logo_url TEXT,
    cover_image_url TEXT,
    emergency_available BOOLEAN DEFAULT TRUE,
    onboarding_status_id integer,
    over_view TEXT,
    organization_id integer NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT hospital_pkey PRIMARY KEY (hospital_id),
    CONSTRAINT hospital_onboarding_status_fk FOREIGN KEY (onboarding_status_id)
        REFERENCES ponntrix_hospital.onboarding_status(onboarding_status_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- 11. ADDRESS
CREATE TABLE IF NOT EXISTS ponntrix_hospital.address (
    address_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    address_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    entity_type character varying(30) NOT NULL, -- HOSPITAL, CLINIC, MULTI_SPECIALITY, LAB, PHARMACY
    entity_id integer NOT NULL,
    state_id integer NOT NULL,
    city_id integer NOT NULL,
    area_id integer NOT NULL,
    country_id integer NOT NULL,
    location GEOGRAPHY(POINT, 4326),
    landmark character varying(100),
    address_line1 character varying(100),
    address_line2 character varying(100),
    pincode integer,
    is_primary boolean DEFAULT false,
    is_active boolean DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT address_id_pkey PRIMARY KEY (address_id),
    CONSTRAINT address_unique_key UNIQUE(entity_type, entity_id),
    CONSTRAINT address_country_fk FOREIGN KEY (country_id) REFERENCES ponntrix_hospital.country(country_id),
    CONSTRAINT address_state_fk FOREIGN KEY (state_id) REFERENCES ponntrix_hospital.state(state_id),
    CONSTRAINT address_city_fk FOREIGN KEY (city_id) REFERENCES ponntrix_hospital.city(city_id),
    CONSTRAINT address_area_fk FOREIGN KEY (area_id) REFERENCES ponntrix_hospital.area(area_id)
);

-- 12. DEPARTMENTS
CREATE TABLE IF NOT EXISTS ponntrix_hospital.departments (
    departments_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    department_code character varying(10),
    department_name character varying(50) NOT NULL UNIQUE,
    department_icon_url character varying(100),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT departments_id_pkey PRIMARY KEY (departments_id)
);

-- 13. DOCTOR
CREATE TABLE IF NOT EXISTS ponntrix_hospital.doctor (
    doctor_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    doctor_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    gender character varying(10),
    doctor_phone character varying(12) NOT NULL UNIQUE,
    doctor_email character varying(50) NOT NULL UNIQUE,
    qualification_id integer NOT NULL,
    registration_number character varying(50),
    experience_in_years NUMERIC(10,2) NOT NULL,
    profile_pic_url character varying(255),
    digital_signature_url character varying(255),
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT doctor_id_pkey PRIMARY KEY (doctor_id),
    CONSTRAINT doctor_qualification_fk FOREIGN KEY (qualification_id)
        REFERENCES ponntrix_hospital.qualification(qualification_id)
);

-- 14. DEPARTMENT HEAD
CREATE TABLE IF NOT EXISTS ponntrix_hospital.department_head (
    department_head_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    department_head_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    effective_from TIMESTAMPTZ,
    effective_to TIMESTAMPTZ,
    hospital_id integer NOT NULL,
    doctor_id integer NOT NULL,
    departments_id integer NOT NULL,
    CONSTRAINT department_head_pkey PRIMARY KEY (department_head_id),
    CONSTRAINT department_head_unique_key UNIQUE(departments_id, hospital_id, doctor_id),
    CONSTRAINT department_head_hospital_fk_key FOREIGN KEY (hospital_id)
        REFERENCES ponntrix_hospital.hospital(hospital_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT department_head_dept_fk_key FOREIGN KEY (departments_id)
        REFERENCES ponntrix_hospital.departments(departments_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT department_head_doctor_fk_key FOREIGN KEY (doctor_id)
        REFERENCES ponntrix_hospital.doctor(doctor_id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

-- 15. HOSPITAL DEPARTMENTS
CREATE TABLE IF NOT EXISTS ponntrix_hospital.hospital_departments (
    hospital_departments_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    hospital_departments_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    hospital_id integer NOT NULL,
    departments_id integer NOT NULL,
    department_head_id integer,
    department_email character varying(50) UNIQUE,
    department_phone character varying(12) UNIQUE,
    department_description TEXT,
    floor_no character varying(10),
    room_no character varying(10),
    room_type character varying(10), -- AC / Non-AC
    consultation_fee NUMERIC(10,2),
    premier_consultation_fee NUMERIC(10,2),
    premier_plus_consultation_fee NUMERIC(10,2),
    is_active boolean DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT hospital_departments_id_pkey PRIMARY KEY (hospital_departments_id),
    CONSTRAINT hospital_departments_unique_key UNIQUE(departments_id, hospital_id),
    CONSTRAINT hospital_departments_hospital_fk FOREIGN KEY (hospital_id)
        REFERENCES ponntrix_hospital.hospital(hospital_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT hospital_departments_dept_fk FOREIGN KEY (departments_id)
        REFERENCES ponntrix_hospital.departments(departments_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT hospital_departments_head_fk FOREIGN KEY (department_head_id)
        REFERENCES ponntrix_hospital.department_head(department_head_id) ON UPDATE NO ACTION ON DELETE SET NULL
);

-- 16. DOCUMENTS
CREATE TABLE IF NOT EXISTS ponntrix_hospital.documents (
    documents_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    documents_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    entity_type character varying(30) NOT NULL, --- HOSPITAL, DOCTOR
    entity_id integer NOT NULL,
    documents_name character varying(50),
    document_url_link character varying(255) NOT NULL,
    issued_by character varying(100),
    issued_date TIMESTAMPTZ,
    expiry_date TIMESTAMPTZ,
    is_verified boolean DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT documents_id_pkey PRIMARY KEY (documents_id),
    CONSTRAINT documents_unique_key UNIQUE(entity_type, entity_id, documents_name)
);

-- 17. DOCTOR SPECIALIZATIONS
CREATE TABLE IF NOT EXISTS ponntrix_hospital.doctor_specializations (
    doctor_specializations_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    doctor_specializations_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    doctor_id integer NOT NULL,
    specialization_id integer NOT NULL,
    is_primary boolean DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT doctor_specializations_pkey PRIMARY KEY (doctor_specializations_id),
    CONSTRAINT doctor_specializations_doctor_fk FOREIGN KEY(doctor_id)
        REFERENCES ponntrix_hospital.doctor(doctor_id) ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT doctor_specializations_spec_fk FOREIGN KEY(specialization_id)
        REFERENCES ponntrix_hospital.specialization(specialization_id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

-- 18. HOSPITAL DOCTOR
CREATE TABLE IF NOT EXISTS ponntrix_hospital.hospital_doctor (
    hospital_doctor_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    hospital_doctor_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    hospital_departments_id integer NOT NULL,
    doctor_id integer NOT NULL,
    designation character varying(30),
    joining_date DATE NOT NULL,
    leaving_date DATE,
    consultation_start_time TIME NOT NULL,
    consultation_end_time TIME NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    is_active boolean DEFAULT true,
    is_primary boolean DEFAULT false,
    created_by integer,
    updated_by integer,
    CONSTRAINT hospital_doctor_pkey PRIMARY KEY (hospital_doctor_id),
    CONSTRAINT hospital_doctor_dept_fk FOREIGN KEY(hospital_departments_id)
        REFERENCES ponntrix_hospital.hospital_departments(hospital_departments_id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    CONSTRAINT hospital_doctor_doctor_fk FOREIGN KEY(doctor_id)
        REFERENCES ponntrix_hospital.doctor(doctor_id) ON UPDATE NO ACTION ON DELETE CASCADE
);

-- 19. OPERATING HOURS
CREATE TABLE IF NOT EXISTS ponntrix_hospital.operating_hours (
    operating_hours_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    operating_hours_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    entity_type character varying(30) NOT NULL, -- HOSPITAL, CLINIC, MULTI_SPECIALITY, DEPARTMENT
    entity_id integer NOT NULL,
    day_of_week_id integer NOT NULL,
    opening_time TIME NOT NULL,
    closing_time TIME NOT NULL,
    is_closed boolean DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT operating_hours_pkey PRIMARY KEY (operating_hours_id),
    CONSTRAINT operating_hours_day_fk FOREIGN KEY (day_of_week_id)
        REFERENCES ponntrix_hospital.day_of_week(day_of_week_id)
);

-- 20. HOSPITAL FACILITIES
CREATE TABLE IF NOT EXISTS ponntrix_hospital.hospital_facilities (
    hospital_facilities_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    hospital_facilities_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    hospital_id integer NOT NULL,
    facility_name character varying(50) NOT NULL, -- ICU, Pharmacy, Ambulance, Lab
    description TEXT,
    icon_url character varying(100),
    is_active boolean DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT hospital_facilities_pkey PRIMARY KEY (hospital_facilities_id),
    CONSTRAINT hospital_facilities_fk_key FOREIGN KEY(hospital_id)
        REFERENCES ponntrix_hospital.hospital(hospital_id) ON UPDATE NO ACTION ON DELETE CASCADE
);

-- 21. HOSPITAL REVIEWS
CREATE TABLE IF NOT EXISTS ponntrix_hospital.hospital_reviews (
    hospital_reviews_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    hospital_reviews_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    hospital_id integer NOT NULL,
    patient_id integer,
    rating integer CHECK (rating >= 1 AND rating <= 5),
    review_title character varying(50),
    review_text TEXT,
    is_recommended boolean,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT hospital_reviews_pkey PRIMARY KEY (hospital_reviews_id),
    CONSTRAINT hospital_reviews_fk_key FOREIGN KEY(hospital_id)
        REFERENCES ponntrix_hospital.hospital(hospital_id) ON UPDATE NO ACTION ON DELETE CASCADE
);

-- 22. HOSPITAL REVIEW REPLIES
CREATE TABLE IF NOT EXISTS ponntrix_hospital.hospital_review_replies (
    hospital_review_replies_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    hospital_review_replies_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    hospital_reviews_id integer NOT NULL,
    replied_text TEXT NOT NULL,
    replied_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    replied_by integer,
    updated_by integer,
    CONSTRAINT hospital_review_replies_pkey PRIMARY KEY (hospital_review_replies_id),
    CONSTRAINT hospital_review_replies_fk_key FOREIGN KEY(hospital_reviews_id)
        REFERENCES ponntrix_hospital.hospital_reviews(hospital_reviews_id) ON UPDATE NO ACTION ON DELETE CASCADE
);

-- 23. SOCIAL LINKS
CREATE TABLE IF NOT EXISTS ponntrix_hospital.social_links (
    social_links_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    social_links_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    entity_type character varying(30) NOT NULL, -- HOSPITAL, DOCTOR
    entity_id integer NOT NULL,
    social_media_name character varying(30) NOT NULL, -- facebook, instagram
    social_media_link character varying(200) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT social_links_pkey PRIMARY KEY (social_links_id)
);

-- 24. DOCTOR LANGUAGES
CREATE TABLE IF NOT EXISTS ponntrix_hospital.doctor_languages (
    doctor_languages_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    doctor_languages_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    doctor_id integer NOT NULL,
    language_id integer NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT doctor_languages_pkey PRIMARY KEY (doctor_languages_id),
    CONSTRAINT doctor_languages_doctor_fk FOREIGN KEY(doctor_id)
        REFERENCES ponntrix_hospital.doctor(doctor_id) ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT doctor_languages_language_fk FOREIGN KEY(language_id)
        REFERENCES ponntrix_hospital.languages(language_id) ON UPDATE NO ACTION ON DELETE CASCADE
);

-- 25. DOCTOR CONSULTATION FEE
CREATE TABLE IF NOT EXISTS ponntrix_hospital.doctor_consultation_fee (
    doctor_consultation_fee_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    doctor_consultation_fee_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    hospital_doctor_id integer NOT NULL,
    consultation_fee NUMERIC(10,2),
    premier_consultation_fee NUMERIC(10,2),
    premier_plus_consultation_fee NUMERIC(10,2),
    effective_from TIMESTAMPTZ NOT NULL,
    effective_to TIMESTAMPTZ,
    currency_code character varying(10) DEFAULT 'INR',
    home_visit_available boolean DEFAULT false,
    home_visit_fee NUMERIC(10,2),
    video_consultation_available boolean DEFAULT false,
    video_consultation_fee NUMERIC(10,2),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT doctor_consultation_fee_pkey PRIMARY KEY (doctor_consultation_fee_id),
    CONSTRAINT doctor_consultation_fee_fk_key FOREIGN KEY(hospital_doctor_id)
        REFERENCES ponntrix_hospital.hospital_doctor(hospital_doctor_id) ON UPDATE NO ACTION ON DELETE CASCADE
);

-- 26. DOCTOR AVAILABILITY
CREATE TABLE IF NOT EXISTS ponntrix_hospital.doctor_availability (
    doctor_availability_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    doctor_availability_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    hospital_doctor_id integer NOT NULL,
    day_of_week_id integer NOT NULL,
    session_name character varying(20) NOT NULL, -- MORNING, AFTERNOON, EVENING, NIGHT
    consultation_start_time TIME NOT NULL,
    consultation_end_time TIME NOT NULL,
    slot_duration_minutes integer NOT NULL, -- 15, 30, 45, 60
    available_for_home_visit boolean DEFAULT false,
    available_for_video_consultation boolean DEFAULT false,
    is_active boolean DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT doctor_availability_pkey PRIMARY KEY (doctor_availability_id),
    CONSTRAINT doctor_availability_fk_key FOREIGN KEY(hospital_doctor_id)
        REFERENCES ponntrix_hospital.hospital_doctor(hospital_doctor_id) ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT doctor_availability_day_fk FOREIGN KEY(day_of_week_id)
        REFERENCES ponntrix_hospital.day_of_week(day_of_week_id)
);

-- 27. SLOT TYPE
CREATE TABLE IF NOT EXISTS ponntrix_hospital.slot_type (
    slot_type_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    slot_type_name character varying(50) NOT NULL UNIQUE, -- Consultation, Follow-up, Tele Consultation
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT slot_type_pkey PRIMARY KEY (slot_type_id)
);

-- 28. DOCTOR SLOT STATUS
CREATE TABLE IF NOT EXISTS ponntrix_hospital.doctor_slot_status (
    doctor_slot_status_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    doctor_slot_status_name character varying(50) NOT NULL UNIQUE, -- Available, Blocked, Leave, Booked
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT doctor_slot_status_pkey PRIMARY KEY (doctor_slot_status_id)
);

-- 29. DOCTOR SCHEDULES
CREATE TABLE IF NOT EXISTS ponntrix_hospital.doctor_schedules (
    doctor_schedule_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    hospital_doctor_id integer NOT NULL, -- Links directly to hospital_doctor mapping
    hospital_id integer NOT NULL,
    slot_date DATE NOT NULL,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    slot_type_id integer NOT NULL,
    doctor_slot_status_id integer NOT NULL,
    slot_status character varying(20) DEFAULT 'AVAILABLE',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by INT,
    updated_by INT,
    CONSTRAINT doctor_schedules_pkey PRIMARY KEY (doctor_schedule_id),
    CONSTRAINT doctor_schedules_hosp_doc_fk FOREIGN KEY(hospital_doctor_id)
        REFERENCES ponntrix_hospital.hospital_doctor(hospital_doctor_id) ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT doctor_schedules_hospital_fk FOREIGN KEY(hospital_id)
        REFERENCES ponntrix_hospital.hospital(hospital_id) ON UPDATE NO ACTION ON DELETE CASCADE,
    CONSTRAINT doctor_schedules_slot_type_fk FOREIGN KEY(slot_type_id)
        REFERENCES ponntrix_hospital.slot_type(slot_type_id),
    CONSTRAINT doctor_schedules_status_fk FOREIGN KEY(doctor_slot_status_id)
        REFERENCES ponntrix_hospital.doctor_slot_status(doctor_slot_status_id)
);

-- 30. DOCTOR PRESCRIPTION
CREATE TABLE IF NOT EXISTS ponntrix_hospital.doctor_prescription (
    doctor_prescription_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    doctor_prescription_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    hospital_doctor_id integer NOT NULL,
    appointment_id integer,
    patient_id integer NOT NULL,
    prescription_number character varying(50) NOT NULL UNIQUE,
    diagnosis TEXT NOT NULL,
    chief_complaints TEXT,
    clinical_notes TEXT,
    followup_required BOOLEAN DEFAULT FALSE,
    followup_date DATE,
    advice TEXT,
    status character varying(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT doctor_prescription_pkey PRIMARY KEY (doctor_prescription_id),
    CONSTRAINT doctor_prescription_hosp_doc_fk FOREIGN KEY(hospital_doctor_id)
        REFERENCES ponntrix_hospital.hospital_doctor(hospital_doctor_id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

-- 31. DOCTOR PRESCRIPTION ITEM
CREATE TABLE IF NOT EXISTS ponntrix_hospital.doctor_prescription_item (
    doctor_prescription_item_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    doctor_prescription_item_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    doctor_prescription_id integer NOT NULL,
    medicine_name character varying(100) NOT NULL,
    strength character varying(50),
    dosage_form character varying(50),
    dosage_quantity NUMERIC(10,2),
    dosage_unit character varying(20),
    route character varying(50),
    frequency_per_day integer,
    course_duration_in_days integer,
    total_quantity NUMERIC(10,2),
    morning boolean DEFAULT false,
    afternoon boolean DEFAULT false,
    evening boolean DEFAULT false,
    night boolean DEFAULT false,
    before_food boolean DEFAULT false,
    after_food boolean DEFAULT false,
    with_food boolean DEFAULT false,
    sos boolean DEFAULT false,
    weekly boolean DEFAULT false,
    monthly boolean DEFAULT false,
    alternative_days boolean DEFAULT false,
    instruction TEXT,
    refill_allowed boolean DEFAULT false,
    refill_count integer DEFAULT 0,
    is_substitute_allowed boolean DEFAULT false,
    status character varying(20) DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    CONSTRAINT doctor_prescription_item_pkey PRIMARY KEY (doctor_prescription_item_id),
    CONSTRAINT doctor_prescription_item_fk_key FOREIGN KEY(doctor_prescription_id)
        REFERENCES ponntrix_hospital.doctor_prescription(doctor_prescription_id) ON UPDATE NO ACTION ON DELETE CASCADE
);

-- ==========================================
-- INDEXES FOR GEOSPATIAL & SLOTS SEARCH
-- ==========================================
CREATE INDEX IF NOT EXISTS idx_address_location ON ponntrix_hospital.address USING GIST (location);
CREATE INDEX IF NOT EXISTS idx_doctor_schedule_date ON ponntrix_hospital.doctor_schedules (hospital_doctor_id, hospital_id, slot_date);
CREATE INDEX IF NOT EXISTS idx_hospital_doctor_lookup ON ponntrix_hospital.hospital_doctor (hospital_departments_id, doctor_id);