server:
  port: 8091

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-admin:eureka-admin123@localhost:8100/eureka/
jwt:
  rsa:
    private-key: classpath:private_key.pem
    public-key: classpath:public_key.pem
    expiration: 86400000        # 24 hours in milliseconds
    refresh-expiration: 604800000 # 7 days in milliseconds

spring:
  application:
    name: admin-user-service

  datasource:
    url: jdbc:postgresql://187.127.156.147:5436/admin_db
    username: admin_user
    password: admin_password
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
