CREATE SCHEMA IF NOT EXISTS ponntrix_admin_users;
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1. ORGANIZATION
CREATE TABLE IF NOT EXISTS ponntrix_admin_users.organization (
    organization_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    organization_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    organization_code character varying(50) UNIQUE,
    organization_name character varying(50) NOT NULL,
    organization_type character varying(50) NOT NULL, -- PONNTRIX, FRANCHISE, HOSPITAL
    parent_organization_id integer,
    gst_number character varying(50),
    registration_number character varying(50),
    mobile_number character varying(50),
    email character varying(50),
    is_active boolean DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT organization_pkey PRIMARY KEY (organization_id)
);

-- 2. EMPLOYEE
CREATE TABLE IF NOT EXISTS ponntrix_admin_users.employee (
    employee_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    employee_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    employee_code character varying(50) UNIQUE NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    middle_name VARCHAR(100),
    gender character varying(20), -- MALE, FEMALE
    dob DATE,
    mobile character varying(20) UNIQUE NOT NULL,
    email VARCHAR(150) UNIQUE,
    profile_photo_url character varying(255),
    qualification integer,
    specialization integer,
    experience_years INTEGER,
    is_active BOOLEAN DEFAULT TRUE,
    employee_type character varying(50), --- NURSE, LAB TECHNICIAN, PHARMACIST
    entity_id integer, -- hospitalId, labId, pharmacyId where employee is working
    organization_id integer NOT NULL, -- PONNTRIX--main, FRANCHISE, HOSPITAL
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_by integer,
    created_by integer,
    CONSTRAINT employee_pkey PRIMARY KEY (employee_id)
);

-- 3. PERMISSIONS
CREATE TABLE IF NOT EXISTS ponntrix_admin_users.permissions (
    permission_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    permission_name character varying(100) NOT NULL UNIQUE,
    created_by integer,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_by integer,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT permissions_pkey PRIMARY KEY (permission_id)
);

-- 4. ROLES
CREATE TABLE IF NOT EXISTS ponntrix_admin_users.roles (
    role_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role_name character varying(100) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_by integer,
    CONSTRAINT roles_pkey PRIMARY KEY (role_id)
);

-- 5. ROLE PERMISSIONS
CREATE TABLE IF NOT EXISTS ponntrix_admin_users.role_permissions (
    role_permission_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role_id integer NOT NULL,
    permission_id integer NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    CONSTRAINT role_permissions_pkey PRIMARY KEY (role_permission_id),
    CONSTRAINT fk_permission FOREIGN KEY (permission_id)
        REFERENCES ponntrix_admin_users.permissions (permission_id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_role FOREIGN KEY (role_id)
        REFERENCES ponntrix_admin_users.roles (role_id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT uq_role_permission UNIQUE (role_id, permission_id)
);

-- 6. USERS
CREATE TABLE IF NOT EXISTS ponntrix_admin_users.users (
    users_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username character varying(100) UNIQUE NOT NULL,
    password character varying(255) NOT NULL,
    user_id integer NOT NULL, -- hospitalId, nurse, pharmacistId, doctor_id
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_by integer,
    is_active BOOLEAN DEFAULT false,
    user_type character varying(50), -- 'EMPLOYEE', 'MERCHANT', 'DRIVER', 'CUSTOMER', 'OUTLET'
    CONSTRAINT users_pkey PRIMARY KEY (users_id)
);

-- 7. USER ROLES
CREATE TABLE IF NOT EXISTS ponntrix_admin_users.user_roles (
    user_role_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role_id integer NOT NULL,
    users_id integer NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_role_id),
    CONSTRAINT user_role_fkey FOREIGN KEY (role_id)
        REFERENCES ponntrix_admin_users.roles (role_id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT user_roles_fkey FOREIGN KEY (users_id)
        REFERENCES ponntrix_admin_users.users (users_id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT uq_user_role UNIQUE (users_id, role_id)
);

-- 8. EMPLOYEE ORGANIZATION
CREATE TABLE IF NOT EXISTS ponntrix_admin_users.employee_organization (
    employee_organization_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    employee_organization_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    employee_id integer NOT NULL,
    organization_id integer NOT NULL,
    organization_type character varying(50), -- PONNTRIX, FRANCHISE, HOSPITAL
    department_id integer,
    CONSTRAINT employee_organization_pkey PRIMARY KEY (employee_organization_id),
    CONSTRAINT fk_employee_organization_org FOREIGN KEY (organization_id)
        REFERENCES ponntrix_admin_users.organization(organization_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_employee_organization_emp FOREIGN KEY (employee_id)
        REFERENCES ponntrix_admin_users.employee(employee_id)
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

-- 9. EMPLOYEE SHIFT
CREATE TABLE IF NOT EXISTS ponntrix_admin_users.employee_shift (
    employee_shift_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    employee_shift_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    employee_id integer,
    shift_name VARCHAR(100),
    shift_start TIME,
    shift_end TIME,
    week_off_id integer,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT employee_shift_pkey PRIMARY KEY(employee_shift_id),
    CONSTRAINT employee_shift_emp_fkey FOREIGN KEY (employee_id)
        REFERENCES ponntrix_admin_users.employee (employee_id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

-- 10. EMPLOYEE SPECIALIZATION
CREATE TABLE IF NOT EXISTS ponntrix_admin_users.employee_specialization (
    employee_specialization_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    employee_specialization_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    employee_id integer,
    specialization integer,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    created_by integer,
    updated_by integer,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT employee_specialization_pkey PRIMARY KEY(employee_specialization_id),
    CONSTRAINT employee_specialization_emp_fkey FOREIGN KEY (employee_id)
        REFERENCES ponntrix_admin_users.employee (employee_id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

-- 11. EMPLOYEE LOGIN HISTORY
CREATE TABLE IF NOT EXISTS ponntrix_admin_users.employee_login_history (
    employee_login_history_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    employee_login_uuid UUID DEFAULT gen_random_uuid() NOT NULL UNIQUE,
    employee_id integer,
    login_time TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    logout_time TIMESTAMPTZ,
    ip_address character varying(100),
    device_name character varying(100),
    device_type character varying(50),
    browser character varying(100),
    CONSTRAINT employee_login_history_pkey PRIMARY KEY(employee_login_history_id),
    CONSTRAINT employee_login_history_emp_fkey FOREIGN KEY (employee_id)
        REFERENCES ponntrix_admin_users.employee (employee_id)
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

-- INDEXES
CREATE INDEX IF NOT EXISTS idx_employee_organization_id ON ponntrix_admin_users.employee(organization_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_users_id ON ponntrix_admin_users.user_roles(users_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_role_id ON ponntrix_admin_users.user_roles(role_id);
CREATE INDEX IF NOT EXISTS idx_role_permissions_role_id ON ponntrix_admin_users.role_permissions(role_id);
CREATE INDEX IF NOT EXISTS idx_users_entity_lookup ON ponntrix_admin_users.users(user_id, user_type);